name: Main workflow

on:
  push:
    branches: "**"
    tags: "**"
  pull_request:

jobs:
  markdownlint:
    name: MarkdownLint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint README
        uses: avto-dev/markdown-lint@v1.3.0
        with:
          args: "README.md"
